from typing import List

from fastapi import APIRouter, HTTPException

from app import database
from app.schemas.device_schema import NotificationResponse

router = APIRouter(prefix="/api/notifications", tags=["Notifications"])


@router.get(
    "",
    response_model=List[NotificationResponse],
    summary="List all notifications",
    description="Return the most recent notifications generated by the IoT trust drift system.",
)
async def list_notifications():
    return await database.get_notifications()


@router.get(
    "/{device_id}",
    response_model=List[NotificationResponse],
    summary="List notifications for a device",
    description="Return notifications generated for a single device.",
    responses={404: {"description": "No notifications found for this device"}},
)
async def get_notifications(device_id: str):
    notifications = await database.get_notifications_for_device(device_id)
    if not notifications:
        raise HTTPException(status_code=404, detail="No notifications found for this device")
    return notifications
